cardfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('accounts/',include("accounts.urls")),
    path('collection/',include("collection.urls")),
    path('dashboard/',include("dashboard.urls"))
]

collection/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.my_collection_view, name="my_collection"),
    path("add/", views.add_card_view, name="add_card"),
    path("sell/<int:usercard_id>",views.sell_card_view,name="sell_card"),
]

core/urls.py
from django.urls import path
from .views import landing_page_view,learn_more_view

urlpatterns = [
    path("",landing_page_view,name="home"),
    path("learn-more/",learn_more_view,name="learn-more")
]

cards/models.py
from django.db import models

# Create your models here.

class Card(models.Model):
    FINISH_CHOICES = [
        ("foil", "Foil"),
        ("nonfoil", "Non-Foil"),
    ]
    name = models.CharField(max_length=255)
    scryfall_id = models.CharField(max_length=50)
    finish = models.CharField(
        max_length=10,
        choices=FINISH_CHOICES
    )
    set_code = models.CharField(max_length=10)
    set_name = models.CharField(max_length=100)
    rarity = models.CharField(max_length=50)
    collector_number = models.CharField(max_length=20)
    image_url = models.URLField(null=True, blank=True)
    price_usd = models.DecimalField(
        max_digits=10,decimal_places=2,null=True,blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["scryfall_id", "finish"],
                name="unique_card_printing"
            )
        ]

    def __str__(self):
        return f"{self.name} ({self.set_code})"

collection/models.py
from django.db import models
from cards.models import Card
from django.conf import settings

# Create your models here.

class UserCard(models.Model):
    """
    Represents a card owned by a user as part of their collection.

    This model links a user to a specific card printing and stores
    collection-specific data such as quantity and purchase price.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
        related_name="collection"
    )

    card = models.ForeignKey(
        Card,
        on_delete = models.CASCADE,
        related_name="owners"
    )

    quantity = models.PositiveIntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user","card"],
                name="unique_user_card"
            )
        ]

    def __str__(self):
        return f"{self.user} owns {self.quantity} x {self.card}"
    
class CardTransaction(models.Model):
    BUY = "buy"
    SELL = "sell"

    TRANSACTION_TYPES = [
        (BUY,"Buy"),
        (SELL,"Sell"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="card_transactions"
    )

    card = models.ForeignKey(
        Card,
        on_delete=models.CASCADE,
        related_name="transactions"
    )

    transaction_type = models.CharField(
        max_length=10,
        choices=TRANSACTION_TYPES
    )

    quantity = models.PositiveIntegerField()

    price_per_unit = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        sign = "+" if self.transaction_type == self.BUY else "-"
        return f"{self.user} {sign}{self.quantity} {self.card}"

collection/forms.py
from django import forms

class AddCardForm(forms.Form):
    """
    Form used to add a Magic: The Gathering card to a user's collection.

    Collects the minimum required data to identify an exact card printing
    and the quantity to add.
    """
    set_code = forms.CharField(
        max_length=10,
        label="Set code",
        help_text="Example: sld, mh3, cmm"
    )

    collector_number = forms.CharField(
        max_length=20,
        label="Collector number",
        help_text="Example: 2008, 12a"
    )

    quantity = forms.IntegerField(
        min_value=1,
        initial=1,
        label="Quantity"
    )

    purchase_price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        label="Purchase price"
    )

    is_foil = forms.BooleanField(
        required=False,
        initial=False,
        label="Foil version"
    )

collection/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from collection.forms import AddCardForm
from collection.services.transaction_service import apply_card_transaction
from collection.services.portfolio_service import get_current_portfolio_value
from cards.services.card_importer import import_exact_mtg_card
from collection.models import UserCard
from django.core.paginator import Paginator
from django.db.models import F, Sum, DecimalField, ExpressionWrapper
from collection.models import CardTransaction
from cards.models import Card
from django.contrib import messages

@login_required
def my_collection_view(request):
    form = AddCardForm()

    query = request.GET.get("q","").strip()

    collection_qs = (
        request.user.collection
        .select_related("card").annotate(
            subtotal = ExpressionWrapper(
                F("quantity") * F("card__price_usd"),
                output_field=DecimalField(max_digits=12,decimal_places=2)
            )
        )
    )

    if query:
        collection_qs = collection_qs.filter(
            card__name__icontains=query
        )
        
    collection_qs = collection_qs.order_by("card__name")

    paginator = Paginator(collection_qs,10)
    page_number = request.GET.get("page")
    collection_page = paginator.get_page(page_number)
    
    most_expensive_card = (
        UserCard.objects
        .filter(
            user = request.user,
            card__price_usd__isnull = False
        )
        .select_related("card")
        .order_by("-card__price_usd")
        .first()
    )

    total_value = get_current_portfolio_value(request.user)

    return render(request, "collection/my_collection.html", {
        "form": form,
        "collection": collection_page,
        "most_expensive_card": most_expensive_card,
        "query": query,
        "total_value": total_value,
    })

@login_required
def add_card_view(request):
    """
    Allows an authenticated user to add a card to their collection.
    """
    if request.method != "POST":
        return redirect("my_collection")
    
    form = AddCardForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data

        try:
            card = import_exact_mtg_card(
                set_code=data["set_code"],
                collector_number=data["collector_number"],
                is_foil=data["is_foil"]
            )
        except ValueError as e:
            messages.error(request, str(e), extra_tags="import-error")
            return redirect("my_collection")
        
        apply_card_transaction(
            user=request.user,
            card=card,
            transaction_type=CardTransaction.BUY,
            quantity=data["quantity"],
            price_per_unit=data.get("purchase_price")
        )

        messages.success(request, "Card added to your collection!",extra_tags="import-success")
        return redirect("my_collection")

@login_required
def sell_card_view(request, usercard_id):
    if request.method != "POST":
        return redirect("my_collection")
    
    quantity = int(request.POST["quantity"])
    price = request.POST["price_per_unit"]

    card = Card.objects.get(id=usercard_id)

    try:
        apply_card_transaction(
            user=request.user,
            card=card,
            transaction_type=CardTransaction.SELL,
            quantity=quantity,
            price_per_unit=price,
        )
    except ValueError as e:
        messages.error(request, str(e), extra_tags="sell-error")
        return redirect("my_collection")

    messages.success(request, "Collection updated!",extra_tags="sell-success")
    return redirect("my_collection")




 

collection/templates/collection/my_collection.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}My Collection{% endblock  %}
{% block styles %} <link rel="stylesheet" href="{% static "collection/my_collection.css" %}">{% endblock  %}

{% block content %}
  <div class="collection-top">
    <div class="collection-add">
      {% for message in messages %}
        {% if "import-error" in message.tags %}
          <div class="message error">
            {{ message }}
          </div>
        {% elif "import-success" in message.tags %}
          <div class="message success">
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
      <form method="post" action="{% url 'add_card' %}" class="collection-form">
        {% csrf_token %}
        <div class="form-row">
          <div class="field">
            {{ form.set_code.label_tag }}
            {{ form.set_code }}
          </div>

          <div class="field">
            {{ form.collector_number.label_tag }}
            {{ form.collector_number }}
          </div>
          
          <div class="field">
            {{ form.quantity.label_tag }}
            {{ form.quantity }}
          </div>

          <div class="field">
            {{ form.purchase_price.label_tag }}
            {{ form.purchase_price }}
          </div>

          <div class="field checkbox-field">
            {{ form.is_foil.label_tag }}
            {{ form.is_foil }}
          </div>

        </div>

        <button type="submit">Add card</button>
      </form>
    </div>
    {% if collection %}
      <div class="expensive-card">
        <h3> Top card: {{ most_expensive_card.card.price_usd }} USD </h3>
        <div class="card-tile">
          <img src="{{ most_expensive_card.card.image_url }}" alt="{{ most_expensive_card.card.name }}" loading="lazy">
            <div class="card-overlay">
              <span>{{ most_expensive_card.card.set_code|upper }}</span>
            </div>
          </div>
      </div>
    {% else %}
      <h3> Add your first card! </h3>
    {% endif %}
</div>

  <form method="get" class="collection-search">
    <input
      type="text"
      name="q"
      placeholder="Search card..."
      value="{{ query }}"
    >

    <button type="submit">Search</button>

    {% if query %}
      <a href="{% url 'my_collection' %}" class="clear-search">
        Clear
      </a>
    {% endif %}
  </form>
  
  {% if query %}
    <span>Total collection value: — </span>
  {% else %}
    <span>Total collection value: {{ total_value }} USD</span>
  {% endif %}

  {% for message in messages %}
    {% if "sell-error" in message.tags %}
      <div class="message error">
        {{ message }}
      </div>
    {% elif "sell-success" in message.tags %}
      <div class="message success">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}

  <div class="collection-list">
    <div class="collection-header-row">
      <span>Name</span>
      <span>Qty</span>
      <span>Market price / und</span>
      <span>Subtotal</span>
      <span>Sell</span>
    </div>

    {% for uc in collection %}
      <div class="collection-row">
        <span class="card-name-wrapper">
          <span class="card-name">
            {{ uc.card.name }}
            <small>
              ({{ uc.card.get_finish_display }})
            </small>
          </span>
          <img 
          src="{{ uc.card.image_url }}"
          alt="{{ uc.card.name }}"
          class="card-preview"
          loading="lazy"
          >
        </span>
        <span>x{{ uc.quantity }}</span>
        <span>
          {% if uc.card.price_usd %}
            ${{ uc.card.price_usd }}
          {% else %}
            —
          {% endif %}
        </span>
        <span>
          {% if uc.subtotal %}
            {{ uc.subtotal }}
          {% else %}
            —
          {% endif %}
        </span>
        <form class="sell-form" method="post" action="{% url 'sell_card' uc.card.id %}">
          {% csrf_token %}

          <input
            type="number"
            name="quantity"
            min="1"
            max="{{ item.quantity }}"
            placeholder="Qty"
            required
          >

          <input
            type="number"
            step="0.01"
            name="price_per_unit"
            placeholder="Sell price"
            required
          >

          <button type="submit">Sell</button>
        </form>
      </div>
    {% empty %}
      <p class="empty-state">Your collection is empty.</p>
    {% endfor %}
    </div>
    <div class="pagination">
        {% if collection.has_previous %}
          <a href="?q={{ query }}&page={{ collection.previous_page_number }}"> Previous </a>
        {% endif %}

        <span>
          Page {{ collection.number }} of {{ collection.paginator.num_pages }}
        </span>

        {% if collection.has_next %}
          <a href="?q={{ query }}&page={{ collection.next_page_number }}">Next</a>
        {% endif %}
      </div>

{% endblock  %}